"""
API-facing manager for the multi-agent pipeline (separate from solo AgentManager).
"""

from __future__ import annotations

import asyncio

from google.genai import types as genai_types

try:
    from google.adk import Runner
    from google.adk.sessions import InMemorySessionService
except ImportError:
    Runner = None
    InMemorySessionService = None

from src.common.logger import get_logger
from src.serving.agent.common import create_mcp_toolset
from src.serving.agent.multi_agent.memory import ConversationMemory
from src.serving.agent.multi_agent.pipeline import build_multi_agent_pipeline

logger = get_logger(__name__)

APP_NAME = "MultiAgentFinancialIntelligence"
USER_ID = "api_multi_agent_user"
SESSION_ID = "api_multi_agent_session"


class MultiAgentManager:
    """Lazy-initialized multi-agent pipeline for HTTP/API use."""

    def __init__(self):
        self._initialized = False
        self.mcp_toolset = None
        self.runner = None
        self.session_service = None
        self.memory = ConversationMemory()

    async def initialize(self) -> None:
        if self._initialized:
            return
        if Runner is None:
            raise RuntimeError("Google ADK is not installed.")

        logger.info("Initializing MultiAgentManager...")
        self.mcp_toolset = create_mcp_toolset(timeout=150)
        root_agent = build_multi_agent_pipeline(self.mcp_toolset)
        self.session_service = InMemorySessionService()
        self.runner = Runner(
            agent=root_agent,
            app_name=APP_NAME,
            session_service=self.session_service,
        )
        await self.session_service.create_session(
            app_name=APP_NAME,
            user_id=USER_ID,
            session_id=SESSION_ID,
        )
        self._initialized = True
        logger.info("MultiAgentManager ready.")

    async def chat(self, message: str) -> str:
        await self.initialize()

        context_block = self.memory.format_for_planner()
        if context_block:
            message_text = f"{context_block}\n\nCurrent question:\n{message}"
        else:
            message_text = message

        content = genai_types.Content(
            role="user",
            parts=[genai_types.Part(text=message_text)],
        )

        final_text = ""
        async for event in self.runner.run_async(
            user_id=USER_ID,
            session_id=SESSION_ID,
            new_message=content,
        ):
            if event.is_final_response():
                if event.content and event.content.parts:
                    for part in event.content.parts:
                        if hasattr(part, "text") and part.text:
                            final_text += part.text

        self.memory.add_turn(message, final_text)
        return final_text or "No response generated by the multi-agent pipeline."

    async def shutdown(self) -> None:
        if self.mcp_toolset:
            close_result = self.mcp_toolset.close()
            if asyncio.iscoroutine(close_result):
                await close_result
        self._initialized = False


multi_agent_manager = MultiAgentManager()
